### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by bertocus** [Touwhaar/JetBrains#1]
pls help, when i run i get this error
![image](https://user-images.githubusercontent.com/44570333/197297470-f511e494-1410-4674-b0f5-80d9e6774e27.png)

**Comment by Gertje823** [comment]
I got the same error :(

**Comment by bastiaanbiester** [comment]
it can't count to any number, please help and fix again.
![image](https://user-images.githubusercontent.com/44570333/197297783-0e64f8cc-bf42-4cff-805b-1bd56ea36211.png)
